version: '3'

services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql
    environment:
      MYSQL_DATABASE: bank
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mysql/sql:/data/sql